### ISSUE TITLE
Use a logging mechanism instead of warns and prints

### ISSUE THREAD

**Issue by moltar** [jjn1056/DBIx-Class-Migration#44]
I suggest using a logging mechanism, instead of warns and prints. My recommendation would be Log::Any.

However, one caveat is that it does not produce any output by default and needs logging enabled, which maybe not a good idea given that it is a cli tool and might need to communicate with the user.

DH uses Log::Contextual, I am assuming because frew also wrote that. We could use that as well. But I am not understanding it that well. I can't figure out if it is possible to redirect logs elsewhere, if a user chooses to do so. Or turn off completely. Or set different levels at run time.

**Comment by Sweet-kid** [comment]
Hi! 

I've started working on this issue, here is the concerned branch : https://github.com/Sweet-kid/DBIx-Class-Migration/tree/add_logging
For now, I've just replaced all die with $log->error, but one test is failing, https://gist.github.com/Sweet-kid/dd27b4299d3810002e89
I'm unable to figure out why it's not failing when I'm using die instead of $log->error. This line https://github.com/Sweet-kid/DBIx-Class-Migration/blob/add_logging/lib/DBIx/Class/Migration.pm#L226 is getting executed in case of die as well & it should give the same error in both the cases. I'll try to debug more, but in case if you've idea about the reason, then please let me know.
Also, if you want me to use anything else apart from Log::Any, then please let me know. 

Thanks.

**Comment by moltar** [comment]
@Sweet-kid it seems like the test is actually testing the exception. The test expects program to `die`. When you do `$log->error()`, it does not actually die, but simply log the fact that there was an error.

What you want to do is to log and then die anyways.

**Comment by jjn1056** [comment]
@Sweet-kid   I do like what frew is saying about Log::contextual.  I just never had time to go figure it out ;)  But in general something that works however DBIC::Deployment handler works is I think the right idea. Ideally people can start with DBICM and then move on to do something custom with DH when they find they outgrow it.
