### ISSUE TITLE
Can't pass schema options in a Runscript script

### ISSUE THREAD

**Issue by felliott** [jjn1056/DBIx-Class-Migration#54]
Hey @jjn1056,

I'm using DBICM with Postgres and making use of Pg's schemas.  When I write migration scripts in perl using DBICM::Runscript I'm unable to access my resultsets because they are not in a public schema.  To get around this, I need to pass the `db_schema` and `moniker_parts` options to the call to `DBIx::Class::Schema::Loader::make_schema_at` in [DBICM::RunScript::Trait::SchemaLoader](https://metacpan.org/source/JJNAPIORK/DBIx-Class-Migration-0.057/lib/DBIx/Class/Migration/RunScript/Trait/SchemaLoader.pm#L13), but the options are hardcoded in `DBICM::SchemaLoader::opts`.

I wasn't able to figure out a way to pass these options, so for now I've settled for monkeypatching the call to `opts` like so:

``` perl
no warnings redefine;                                                                                                                                                                                    
my @orig_opts = DBIx::Class::Migration::SchemaLoader::opts();                                                                                                                                               
*DBIx::Class::Migration::SchemaLoader::opts                                                                                                                                                                 
    = sub { (@orig_opts, 'db_schema', ['public','study_design', 'bioware'],                                                                                                                                 
             'moniker_parts', ['schema', 'name']) };     
```

Is there a better way to do this?  If not, would you like a doc patch for the FAQ showing how to do this?  Thank you!

Cheers,
Fitz

**Comment by jjn1056** [comment]
Fitz,
Hmm let me think about it, I'd like a better way to facilitate.   If I can think of something better I'll add a cookbook entry!
Jnap 


     On Sunday, June 7, 2015 5:02 PM, Fitz Elliott <notifications@github.com> wrote:
   

 Hey @jjn1056,I'm using DBICM with Postgres and making use of Pg's schemas. When I write migration scripts in perl using DBICM::Runscript I'm unable to access my resultsets because they are not in a public schema. To get around this, I need to pass the db_schema and moniker_parts options to the call to DBIx::Class::Schema::Loader::make_schema_at in DBICM::RunScript::Trait::SchemaLoader, but the options are hardcoded in DBICM::SchemaLoader::opts.I wasn't able to figure out a way to pass these options, so for now I've settled for monkeypatching the call to opts like so:no warnings redefine;                                                                                                                                                                                    
my @orig_opts = DBIx::Class::Migration::SchemaLoader::opts();                                                                                                                                               
*DBIx::Class::Migration::SchemaLoader::opts                                                                                                                                                                 
    = sub { (@orig_opts, 'db_schema', ['public','study_design', 'bioware'],                                                                                                                                 
             'moniker_parts', ['schema', 'name']) };     Is there a better way to do this? If not, would you like a doc patch for the FAQ showing how to do this? Thank you!Cheers,
Fitz—

**Comment by mohawk2** [comment]
The way forward would be analogous to https://metacpan.org/pod/distribution/DBIx-Class-Migration/lib/DBIx/Class/Migration/Script/Help/extra_schemaloader_args.pod in ::Script. @felliott If you're willing to say what code you'd like to be able to write in order to get your args used, then it can be made so!

However, without that, I'm a bit helpless, so I'll close till the above is specified.
