### ISSUE TITLE
Can't run 

### ISSUE THREAD

**Issue by davehodg** [jjn1056/DBIx-Class-Migration#59]
failed to run Perl in /Users/daveh/workspace/DBIx-Class-Migration/t/share/migrations/MySQL/deploy/1/002-artists.pl: Can't locate object method "dump_config_sets" via package "DBIx::Class::Fixtures=HASH(0x7f89793ae1d0)" (perhaps you forgot to load "DBIx::Class::Fixtures=HASH(0x7f89793ae1d0)"?) at lib/DBIx/Class/Migration/RunScript/Trait/Dump.pm line 22.

$ cpanm DBIx::Class::Fixtures
DBIx::Class::Fixtures is up to date. (1.001032)

Adding use DBIx::Class::Fixtures; to t/migration-mysql.t fixes this error.

**Comment by SysPete** [comment]
I've been investigating this further and it seems that the cause is due to changed behaviour in Perl >= 5.18. Quoting from https://metacpan.org/pod/distribution/perl/pod/perlvar.pod#ENV :

`As of v5.18.0, both keys and values stored in %ENV are stringified.`

This is a problem since the Dump and Populate traits are passed the DBIC::Fixtures object via %ENV so the object is stringified into "DBIx::Class::Fixtures=HASH(0x...)" as per initial issue comment. I'll create a PR with TODO blocks for Perl>=5.18 for the MySQL tests and then hopefully try and find an alternative approach.

**Comment by SysPete** [comment]
@jjn1056 since DCF obj is hash-based then serializing to something text-based and recreating the obj in the Dump and Populate Traits would seem least-invasive. Any preference for serializer? I'm happy to create PR especially as I have DCM for my December CPAN PR challenge so am looking for things to fix.

**Comment by jjn1056** [comment]
Hey,
I like JSON for serialization but plain old Perl is great as well and requires the least additional stuff I think?   give it a try.  I'll try to get to your existing PR, just been busy with home stuff and was taking some time away from open source -jnap 


    On Tuesday, December 1, 2015 11:52 AM, Peter Mottram <notifications@github.com> wrote:
 

 @jjn1056 since DCF obj is hash-based then serializing to something text-based and recreating the obj in the Dump and Populate Traits would seem least-invasive. Any preference for serializer? I'm happy to create PR especially as I have DCM for my December CPAN PR challenge so am looking for things to fix.—

**Comment by SysPete** [comment]
I've cancelled the PR with the TODO blocks and am now testing a new patch using JSON::XS as serializer since that is an existing dep. More new soon I hope...

**Comment by SysPete** [comment]
@jjn1056 I'm happy with current state of PR #68 which passes things through ENV as JSON and then reconstructs the objects at the far side. I won't be making further changes unless there is anything there you are not happy with.
