### ISSUE TITLE
MySQL test fails

### ISSUE THREAD

**Issue by davehodg** [jjn1056/DBIx-Class-Migration#60]
ok 3 - can correctly infer a database DBD
Cannot overwrite '/Users/daveh/workspace/DBIx-Class-Migration/t/share/migrations/_source/deploy/1/001-auto.yml', either enable force_overwrite or delete it at /Users/daveh/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 731.

Even if I delete that file before running the test.

**Comment by SysPete** [comment]
Other files will be left lying around as well when tests fails due to #59 and so DH gets messed up as you are seeing. I've submitted PR #68 which fixes #59 and so also this issue should be cleared.

@davehodg I'll ping you on this issue once @jjn1056 has (hopefully) merged the PR and made a new release.

**Comment by davehodg** [comment]
I've left this behind. I was interested as part of the CPAN PR challenge but I found nothing I could contribute to.

**Comment by mohawk2** [comment]
I will close this, but if issues remain or recur please reopen. Thanks!
