### ISSUE TITLE
unexpected error "Use of uninitialized value $sharedir in concatenation"

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#77]
In the doc on the [page](http://search.cpan.org/~jjnapiork/DBIx-Class-Migration-0.058/lib/DBIx/Class/Migration/Tutorial/FirstMigration.pod) you say:
>Before we move on, let's see the status of your schema and database:
    dbic-migration -Ilib status

After running this command I got this instead:
```
Use of uninitialized value $sharedir in concatenation (.) or string at /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/DBIx/Class/Migration/ShareDirBuilder.pm line 33.
Can't find a share () for ArtCoin at /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/DBIx/Class/Migration/ShareDirBuilder.pm line 33.
```

**Comment by mohawk2** [comment]
You are right. Since 0.025, when the tutorial was written, I think the sharedir is now only lazily built. A number of other things have changed a bit too. However, I don't feel it's different in important enough ways to justify a rejig. If you feel differently, please do run through the tutorials and update them with a PR!

Closing.
