### ISSUE TITLE
Broken links at DBIx::Class::Migration::Script 

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#79]
Different part of documentation have same link. Example: [dsn](http://search.cpan.org/%7Ejjnapiork/DBIx-Class-Migration-0.058/lib/DBIx/Class/Migration/Script.pm#dsn)

**Comment by mohawk2** [comment]
They're not in fact broken. They are duplicated, between `=head2` and `=head3`. MetaCPAN (https://metacpan.org/pod/DBIx::Class::Migration::Script) deals with this fine. Since they are referring to different aspects of exactly the same info (the attribute vs the command flag that controls that attribute), this is not really a problem.

Therefore, closing this. Thanks for the report.
