### ISSUE TITLE
extra_schemaloader_args not passed through in RunScript::Trait::SchemaLoader::schema()

### ISSUE THREAD

**Issue by pullingshots** [jjn1056/DBIx-Class-Migration#93]
I am passing in the schema loader option 'moniker_map' using the extra_schemaloader_args attribute, but my migration script fails to run because the moniker_map option is not used when creating the schema in the script

`my $migration = DBIx::Class::Migration->new( 
  schema => $schema,
  extra_schemaloader_args => { moniker_map => { pos => 'POs' } },
);`

`migration {
  shift->schema->storage->dbh_do( ... )
}`

throws error:

`failed to run Perl in /vagrant/goldenaxe/share/migrations/PostgreSQL/upgrade/18-19/001-update_functions.pl: Unable to load schema - chosen moniker/class naming style results in moniker clashes. Change the naming style, or supply an explicit moniker_map: tables "public"."po", "public"."pos" reduced to the same source moniker 'Po'`

**Comment by mohawk2** [comment]
Thanks for the report. This is the similar to #54 - like with that, I don't really know what code you'd like to be able to write to see this work.

In particular, the code you've given above seems not to be connected: the `migration` is a function exported by `DBIx::Class::Migration::RunScript`, and has no way of knowing about the `$migration` you defined previously. If you can show the code that might work but currently doesn't (rather than what seems to me like code that couldn't possibly work), that will help - best in the form of an updated or new automated test file, of course :-)

Closing because insufficient info.
